# Generated by Django 5.1 on 2024-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToturialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kurd', models.CharField(max_length=100, verbose_name='نام آموزش کردی')),
                ('title_persian', models.CharField(max_length=100, verbose_name='نام آموزش فارسی')),
                ('title_english', models.CharField(max_length=100, verbose_name='نام آموزش انگلیسی')),
                ('kurd_description', models.TextField(verbose_name='شرح آموزش کردی')),
                ('persian_description', models.TextField(verbose_name='شرح آموزش فارسی')),
                ('english_description', models.TextField(verbose_name='شرح آموزش انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Toturial', verbose_name='عکس آموزش')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
    ]
