# Generated by Django 5.1 on 2024-08-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toturial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toturialmodel',
            options={'verbose_name': 'آموزش', 'verbose_name_plural': 'آموزش ها'},
        ),
    ]
