# Generated by Django 5.0.6 on 2024-06-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicmp3model',
            options={'verbose_name': 'موزیک', 'verbose_name_plural': 'موزیک صوتی'},
        ),
        migrations.AlterModelOptions(
            name='musicvideomodel',
            options={'verbose_name': 'موزیک', 'verbose_name_plural': 'موزیک تصویری'},
        ),
    ]
