# Generated by Django 5.1 on 2024-10-14 09:57

import django.db.models.deletion
import podcast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPodcastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام دسته بندی کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام دسته بندی فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام دسته بندی انگلیسی')),
            ],
            options={
                'verbose_name': 'نام دسته بندی',
                'verbose_name_plural': 'نام دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='SingerPodcastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام گوینده کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام گوینده فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام گوینده انگلیسی')),
            ],
            options={
                'verbose_name': 'نام خواننده',
                'verbose_name_plural': 'نام خواننده',
            },
        ),
        migrations.CreateModel(
            name='PodcastVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام پادکست کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام پادکست فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام پادکست انگلیسی')),
                ('kurd_date', models.CharField(max_length=20, verbose_name='تاریخ کردی')),
                ('persian_date', models.CharField(max_length=20, verbose_name='تاریخ فارسی')),
                ('english_date', models.CharField(max_length=20, verbose_name='تاریخ انگلیسی')),
                ('popularity_rate', models.FloatField(default=0.0, verbose_name='میزان محبوبیت')),
                ('music', models.FileField(upload_to=podcast.models.file_path, verbose_name='پادکست')),
                ('writer_kurd', models.CharField(max_length=50, verbose_name='نویسنده کردی')),
                ('writer_persian', models.CharField(max_length=50, verbose_name='نویسنده فارسی')),
                ('writer_english', models.CharField(max_length=50, verbose_name='نویسنده انگلیسی')),
                ('musictext_kurd', models.CharField(max_length=50, verbose_name='موسیقی متن کردی')),
                ('musictext_persian', models.CharField(max_length=50, verbose_name='موسیقی متن فارسی')),
                ('musictext_english', models.CharField(max_length=50, verbose_name='موسیقی متن انگلیسی')),
                ('compilation_kurd', models.CharField(max_length=50, verbose_name='تدوین کردی')),
                ('compilation_persian', models.CharField(max_length=50, verbose_name='تدوین فارسی')),
                ('compilation_english', models.CharField(max_length=50, verbose_name='تدوین انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=podcast.models.file_path, verbose_name='عکس پادکست')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.categorypodcastmodel', verbose_name='دسته')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.singerpodcastmodel', verbose_name='گوینده')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست صوتی',
            },
        ),
        migrations.CreateModel(
            name='PodcastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام پادکست کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام پادکست فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام پادکست انگلیسی')),
                ('kurd_date', models.CharField(max_length=20, verbose_name='تاریخ کردی')),
                ('persian_date', models.CharField(max_length=20, verbose_name='تاریخ فارسی')),
                ('english_date', models.CharField(max_length=20, verbose_name='تاریخ انگلیسی')),
                ('popularity_rate', models.FloatField(default=0.0, verbose_name='میزان محبوبیت')),
                ('music', models.FileField(upload_to=podcast.models.file_path, verbose_name='پادکست')),
                ('writer_kurd', models.CharField(max_length=50, verbose_name='نویسنده کردی')),
                ('writer_persian', models.CharField(max_length=50, verbose_name='نویسنده فارسی')),
                ('writer_english', models.CharField(max_length=50, verbose_name='نویسنده انگلیسی')),
                ('musictext_kurd', models.CharField(max_length=50, verbose_name='موسیقی متن کردی')),
                ('musictext_persian', models.CharField(max_length=50, verbose_name='موسیقی متن فارسی')),
                ('musictext_english', models.CharField(max_length=50, verbose_name='موسیقی متن انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=podcast.models.file_path, verbose_name='عکس پادکست')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='podcast.categorypodcastmodel', verbose_name='دسته')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer', to='podcast.singerpodcastmodel', verbose_name='گوینده')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست صوتی',
            },
        ),
    ]
