# Generated by Django 5.0.6 on 2024-06-15 08:58

import django.db.models.deletion
import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام بازیگر کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام بازیگر فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام بازیگر انگلیسی')),
            ],
            options={
                'verbose_name': 'نام بازیگران',
                'verbose_name_plural': 'نام بازیگران',
            },
        ),
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام کارگردان کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام کارگردان فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام کارگردان انگلیسی')),
            ],
            options={
                'verbose_name': 'کارگردان',
                'verbose_name_plural': 'کارگردان',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام ژانر کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام ژانر فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام ژانر انگلیسی')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام فیلم کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام فیلم فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام فیلم انگلیسی')),
                ('kurd_date', models.CharField(max_length=20, verbose_name='تاریخ کردی')),
                ('persian_date', models.CharField(max_length=20, verbose_name='تاریخ فارسی')),
                ('english_date', models.CharField(max_length=20, verbose_name='تاریخ انگلیسی')),
                ('kurd_description', models.TextField(verbose_name='خلاصه فیلم کردی')),
                ('persian_description', models.TextField(verbose_name='خلاصه فیلم فارسی')),
                ('english_description', models.TextField(verbose_name='خلاصه فیلم انگلیسی')),
                ('imdb', models.CharField(max_length=5, verbose_name='نمره imdb')),
                ('popularity_rate', models.FloatField(verbose_name='میزان محبوبیت')),
                ('movie', models.FileField(max_length=2000, upload_to=movie.models.file_path, verbose_name='فیلم')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ManyToManyField(to='movie.actormodel', verbose_name='نام بازیگران')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.directormodel', verbose_name='کارگردان')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.genremodel', verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
    ]
