# Generated by Django 5.0.6 on 2024-06-15 09:05

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.file_path, verbose_name='عکس فیلم'),
        ),
    ]
