# Generated by Django 5.0.6 on 2024-06-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_categorymodel_moviemodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='category',
        ),
    ]
