# Generated by Django 5.0.6 on 2024-06-15 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_moviemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.categorymodel', verbose_name='دسته'),
            preserve_default=False,
        ),
    ]
