# Generated by Django 5.0.6 on 2024-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_moviemodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام جایزه کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام جایزه فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام جایزه انگلیسی')),
            ],
            options={
                'verbose_name': 'جایزه ها ',
                'verbose_name_plural': 'جایزه ها ',
            },
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='award',
            field=models.ManyToManyField(to='movie.awardsmodel', verbose_name='جایزه ها '),
        ),
    ]
