# Generated by Django 5.0.6 on 2024-06-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_moviemodel_award_alter_moviemodel_imdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurd', models.CharField(max_length=100, verbose_name='نام تهیه کننده کردی')),
                ('name_persian', models.CharField(max_length=100, verbose_name='نام تهیه کننده فارسی')),
                ('name_english', models.CharField(max_length=100, verbose_name='نام تهیه کننده انگلیسی')),
            ],
            options={
                'verbose_name': 'تهیه کننده ها ',
                'verbose_name_plural': 'تهیه کننده ها ',
            },
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='producer',
            field=models.ManyToManyField(to='movie.producermodel', verbose_name='تهیه کننده ها '),
        ),
    ]
