# Generated by Django 5.1 on 2024-08-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_producermodel_moviemodel_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='award',
            field=models.ManyToManyField(to='movie.awardsmodel', verbose_name='جایزه ها '),
        ),
    ]
